function [sideforcemag,sideforce,axialforce,displacement]=readdata_solid(filepath,...
    parent_dir,spring_height,wire_dia)
%This function will read the txt files generated by abaqus.py and read xlsx
%file obtainted by experimental testing
%and will write the data into corresponding variables
fID = fopen(strcat(filepath,'sideforce.txt'),'r');
fgetl(fID);
more = true;
sideforce = [];
while more
   [data more]=fscanf(fID,'%f',3);
   if more
       sideforce = [sideforce; data'];
   end
end
fclose(fID);
sideforcemag = sqrt(sideforce(:,1).^2+sideforce(:,3).^2);


fID = fopen(strcat(filepath,'axialforce.txt'),'r');
fgetl(fID);
more = true;
axialforce = [];
while more
   [data more]=fscanf(fID,'%f',1);
   if more
       axialforce = [axialforce data];
   end
end
fclose(fID);

fID = fopen(strcat(filepath,'displacement.txt'),'r');
fgetl(fID);
more = true;
displacement = [];
while more
   [data more]=fscanf(fID,'%f',1);
   if more
       displacement = [displacement data];
   end
end
fclose(fID);

% %now reading load_testing_data
% inchestomm =25.4;
% lbftonewton = 4.4482216;
% filename = strcat(parent_dir,'/load_testing_data.xlsx');
% %reading Axial Force data
% height = xlsread(filename,'Sheet1','A:A');% in inches
% displacement_exp = (spring_height+wire_dia)*(ones(length(height),1))-inchestomm*height;
% axialforce_exp = lbftonewton*xlsread(filename,'Sheet1','B:B');
% sideforcemag_exp =  lbftonewton*xlsread(filename,'Sheet2','R:R');
end