% This Mainfile will 
%(0)print readme file with parameters for the current iteration
%(1)Read Profiler data, interpolate to a spline and print coordinate file,
%(2)print abaqus.py file with continumm elements and contacts
%(3)run the python script using abaqus engine,
%(4)read output files generated by abaqus and also from the experiment
%(5)generate plots for side-forces and axial forces wrt displacement
%(6)save all the output to a mat file for the whole parametric space

clc; clear all; close all;

%select the parent directory and read profile data
parent_dir = uigetdir('/export/home/a/deshmuk5/abaqus/MWspring/');

% wire_dia = read_wire_dia_solid(parent_dir);% in mm
wire_dia=[13.5];
plate_thickness=10.0;%in mm

%specifying outer diameters not the central diameters in mm % spring4
dia_start = [93.18];
dia_max1=[94.14];%dia_max1=dia_max1*[(1-0.025/2),(1+0.025/2)];
dia_max2=[130.25];%dia_max2=dia_max2*[(1-0.025/2)];dia_max2=dia_max2*[(1-0.025/2),1,(1+0.025/2)];
dia_max3=[141.32];%dia_max3=dia_max3*[(1-0.025/2),(1+0.025/2)];
dia_max4=[142.70];%dia_max4=dia_max4*[(1-0.025/2),(1+0.025/2)];
dia_max5=[130.95];%dia_max5=dia_max5*[(1+0.025/2)];dia_max5=dia_max5*[(1-0.025/2),1,(1+0.025/2)];
dia_max6=[95.82];%dia_max6=dia_max6*[(1-0.025/2),(1+0.025/2)];
dia_end=[92.76];

dia_min1=[93.01];
dia_min2=[126.21];%dia_min2=dia_min2*[(1-0.025/2),1,(1+0.025/2)];
dia_min3=[140.44];%dia_min3=dia_min3*[(1-0.025/2),1,(1+0.025/2)];
dia_min4=[124.50];%dia_min4=dia_min4*[(1-0.025/2),1,(1+0.025/2)];
dia_min5=[93.25];

angle_pts = [0 100.8 173.9 424.0 522.2 724.5 812.7 930.8 1105.5 1219.3 1461.5 1553.8 1643.1];%in degree
% angle_pts = [0 100 135 424 522 724 812 930 1105 1219 1508 1553 1643];%in degree
% height_pts= [0 0 0 24 38 83 100 125 164 177 196 196 196];% in mm
height_pts= [0 0.9 0.1 24.1 38.3 83.4 100.8 125.1 164.2 177.9 196.7 195.3 196.5];% in mm

%spring3
% dia_start=[94.12];
% dia_max1=[95.77];
% dia_max2=[129.96];%dia_max2=dia_max2*[(1-0.025/2)];%dia_max2=dia_max2*[(1-0.025/2),1,(1+0.025/2)];
% dia_max3=[141.07];%dia_max3=dia_max3*[(1-0.025/2),1,(1+0.025/2)];
% dia_max4=[141.35];%dia_max4=dia_max4*[(1-0.025/2),1,(1+0.025/2)];
% dia_max5=[129.47];%dia_max5=dia_max5*[(1+0.025/2)];%dia_max5=dia_max5*[(1-0.025/2),1,(1+0.025/2)];
% dia_max6=[95.11];
% dia_end=[93.31];
% 
% dia_min1=[93.31];
% dia_min2=[127.25];%dia_min2=dia_min2*[(1-0.025/2),1,(1+0.025/2)];
% dia_min3=[138.74];%dia_min3=dia_min3*[(1-0.025/2),1,(1+0.025/2)];
% dia_min4=[124.15];%dia_min4=dia_min4*[(1-0.025/2),1,(1+0.025/2)];
% dia_min5=[92.95];
% 
% angle_pts = [0 67.5 193 434.7 528.4 729.3 832.4 935.8 1120.3 1234.7 1476.5 1568.6 1647.9];%in degree
% height_pts= [0 1.25 1.72 24.50 40.53 83.88 105.51 128.32 166.70 180.62 196.29 197.41 198.32];% in mm
% height_pts= [0 0 0 24.50 40.53 83.88 105.51 128.32 166.70 180.62 198 198 198];% in mm



% define parameters which will vary and their possible values 
% friction_coeff=[0.3 0.6 1.0 1.5];
friction_coeff=[0.6];
% springyoungmodulus=[200E3 250E3 300E3 350E3];%Mpa
springyoungmodulus=[300E3];%Mpa
% springmeshSize=[5.0 3.0 1.0];
% platemeshSize=[5.0 3.0 1.0];
platemeshSize=[5.0];
springmeshSize=[5.0];

N=500; %number of points for the coordinate file

%create output structure for storing the results
result = struct('wire_dia',{},'spring_height',{},'spring_max_radius',{},'spring_initial_radius',{},'notinterfering',{},...
'sideforce',{},'axialforce',{},'sideforcemag',{},'displacement',{},...
'springyoungmodulus',{},'friction_coeff',{},'springmeshSize',{},'platemeshSize',{},...
'dia_start',{},'dia_max1',{},'dia_max2',{},'dia_max3',{},'dia_max4',{},'dia_max5',{},'dia_max6',{},'dia_end',{},...
    'dia_min1',{},'dia_min2',{},'dia_min3',{},'dia_min4',{},'dia_min5',{},'angle_pts',{},'height_pts',{});

matfilename = strcat(parent_dir,'/result.mat');
keys = {};
values = [];
save(matfilename,'result','keys','values','wire_dia',...
    'springyoungmodulus','friction_coeff','springmeshSize',...
    'dia_start','dia_max1','dia_max2','dia_max3','dia_max4','dia_max5','dia_max6','dia_end',...
    'dia_min1','dia_min2','dia_min3','dia_min4','dia_min5','angle_pts','height_pts');
itotal = 1;
fprintf(strcat(parent_dir,'\n'));
for ids = 1:length(dia_start)
    for idmx1=1:length(dia_max1)
        for idmx2=1:length(dia_max2)
            for idmx3=1:length(dia_max3)
                for idmx4=1:length(dia_max4)
                    for idmx5=1:length(dia_max5)
                        for idmx6=1:length(dia_max6)
                            for ide = 1:length(dia_end)
                                %
                                for idmn1=1:length(dia_min1)
                                    for idmn2=1:length(dia_min2)
                                        for idmn3=1:length(dia_min3)
                                            for idmn4=1:length(dia_min4)
                                                for idmn5=1:length(dia_min5)
                                                    %
                                                    for iE = 1:length(springyoungmodulus)
                                                        for iu =1:length(friction_coeff)
                                                            for ims = 1:length(springmeshSize)
                                                                %print cmd window to text file
                                                                diary(strcat(parent_dir,'/cmdstatus.txt'));
                                                                fprintf(strcat(num2str(itotal),'\n'));
                                                                %if itotal>24
                                                                % to resume from a bad iteration  where x
                                                                %is the last successful iteration
                                                                load(matfilename);
                                                                fprintf(strcat('*** Starting ',char(32),num2str(itotal),' iteration at ',datestr(now),'***\n'));
                                                                %(0)create folder for this case and print out a readme file giving
                                                                %the values of the parameters for this case
                                                                %foldername= strcat('E',num2str(iE),'u',num2str(iu),'m',num2str(ims));
                                                                foldername= strcat('run_',num2str(itotal));
                                                                folderpath= strcat(parent_dir,'/runs/',foldername);
                                                                mkdir(folderpath);
                                                                filepath = strcat(folderpath,'/');
                                                                printreadme_solid(filepath,wire_dia,itotal,springyoungmodulus(iE),...
                                                                    friction_coeff(iu),springmeshSize(ims),platemeshSize(ims),...
                                                                    dia_start(ids),dia_max1(idmx1),dia_max2(idmx2),dia_max3(idmx3),dia_max4(idmx4),dia_max5(idmx5),dia_max6(idmx6),dia_end(ide),...
                                                                    dia_min1(idmn1),dia_min2(idmn2),dia_min3(idmn3),dia_min4(idmn4),dia_min5(idmn5),angle_pts,height_pts);
                                                                fprintf('* Readme file printed *\n');
                                                                %(1)function call for printing the coordinate file
                                                                %(1a)find XYZ
                                                                [X,Y,Z,spring_height,spring_max_radius,spring_initial_radius]=cubicspline_interpolate(filepath,N,dia_start(ids),dia_max1(idmx1),dia_max2(idmx2),dia_max3(idmx3),dia_max4(idmx4),dia_max5(idmx5),dia_max6(idmx6),dia_end(ide),...
                                                                    dia_min1(idmn1),dia_min2(idmn2),dia_min3(idmn3),dia_min4(idmn4),dia_min5(idmn5),angle_pts,height_pts,wire_dia);
                                                                %(1b)
                                                                coordinatefile_solid(filepath,X,Y,Z);
                                                                fprintf('* Coordinate file printed *\n');
                                                                %(2)function call for printing the abaqus.py file
                                                                printpythoncode_solid(filepath,N,wire_dia,spring_height,spring_max_radius,...
                                                                    spring_initial_radius,plate_thickness,springyoungmodulus(iE),friction_coeff(iu),springmeshSize(ims),platemeshSize(ims));
                                                                fprintf('* Abaqus python script printed *\n');
                                                                %(3)run the abaqus.py file
                                                                fprintf('* Submitting job to Abaqus *\n');
                                                                cmdstatus = system(strcat('abaqus cae noGUI=',filepath,'MyModel_solid.py'));
                                                                while cmdstatus
                                                                    %if license not fetched wait
                                                                    fprintf(2,'!!Error: Abaqus Licence not fetched, trying again in 5 sec!!\n');
                                                                    pause(5);% 5sec
                                                                    cmdstatus = system(strcat('abaqus cae noGUI=',filepath,'MyModel_solid.py')); %execute again
                                                                end
                                                                %reading if the geometry was interfering
                                                                fid = fopen(strcat(filepath,'notinterfering.txt'),'r');
                                                                notinterfering = fscanf(fid,'%d');
                                                                fclose(fid);
                                                                
                                                                %(4)function call for reading data from output
                                                                fprintf('* Reading results *\n');
                                                               
                                                                [sideforcemag,sideforce,axialforce,displacement]=readdata_solid(filepath,...
                                                                    parent_dir,spring_height,wire_dia);
                                                                
                                                                %5(5)function call for generating plots
                                                                fprintf('* Generating plots *\n');
                                                                generateplots_solid(filepath,sideforcemag,sideforce,axialforce,displacement);
                                                                
                                                                %(6)save results to the structure
                                                                result(itotal).wire_dia = wire_dia;
                                                                result(itotal).spring_height = spring_height;
                                                                result(itotal).spring_max_radius = spring_max_radius;
                                                                result(itotal).spring_initial_radius= spring_initial_radius;
                                                                result(itotal).notinterfering = notinterfering;
                                                                
                                                                result(itotal).dia_start= dia_start(ids);
                                                                result(itotal).dia_max1= dia_max1(idmx1);
                                                                result(itotal).dia_max2= dia_max2(idmx2);
                                                                result(itotal).dia_max3= dia_max3(idmx3);
                                                                result(itotal).dia_max4= dia_max4(idmx4);
                                                                result(itotal).dia_max5= dia_max5(idmx5);
                                                                result(itotal).dia_max6= dia_max6(idmx6);
                                                                result(itotal).dia_end= dia_end(ide);
                                                                
                                                                result(itotal).dia_min1= dia_min1(idmn1);
                                                                result(itotal).dia_min2= dia_min2(idmn2);
                                                                result(itotal).dia_min3= dia_min3(idmn3);
                                                                result(itotal).dia_min4= dia_min4(idmn4);
                                                                result(itotal).dia_min5= dia_min5(idmn5);
                                                                
                                                                result(itotal).angle_pts= angle_pts;
                                                                result(itotal).height_pts= height_pts;                                                                
                                                                
                                                                result(itotal).sideforce=sideforce;
                                                                result(itotal).axialforce = axialforce';
                                                                result(itotal).displacement = displacement';
                                                                result(itotal).sideforcemag =sideforcemag;
                                                                
                                                                % result(itotal).axialforce_exp = axialforce_exp;
                                                                % result(itotal).displacement_exp = displacement_exp;
                                                                % result(itotal).sideforcemag_exp =sideforcemag_exp;
                                                                
                                                                result(itotal).springyoungmodulus = springyoungmodulus(iE);
                                                                result(itotal).friction_coeff = friction_coeff(iu);
                                                                result(itotal).springmeshSize=springmeshSize(ims);
                                                                result(itotal).platemeshSize=platemeshSize(ims);
                                                                
                                                                values = 1:1:(itotal);
                                                                keys{itotal} = strcat(num2str(ids),num2str(idmx1),num2str(idmx2),num2str(idmx3),num2str(idmx4),num2str(idmx5),num2str(idmx6),num2str(ide),...
                                                                    num2str(idmn1),num2str(idmn2),num2str(idmn3),num2str(idmn4),num2str(idmn5),...
                                                                    num2str(iE),num2str(iu),num2str(ims));
                                                                
                                                                save(matfilename,'result','keys','values','wire_dia',...
                                                                    'springyoungmodulus','friction_coeff','springmeshSize',...
                                                                    'dia_start','dia_max1','dia_max2','dia_max3','dia_max4','dia_max5','dia_max6','dia_end',...
                                                                    'dia_min1','dia_min2','dia_min3','dia_min4','dia_min5','angle_pts','height_pts');
                                                                
                                                                fprintf('* Saving results *\n');
                                                                fprintf(strcat('*** Completed',char(32),num2str(itotal),' iteration at ',datestr(now),' ***\n'));
                                                                fprintf('\n');
                                                                %end
                                                                %to resume from bad iteration
                                                                itotal = itotal+1;
                                                                diary off;
                                                            end
                                                        end
                                                    end
                                                    %
                                                end
                                            end
                                        end
                                    end
                                end
                                %
                            end
                        end
                    end
                end
            end
        end
    end
end

diary off;
%create dictionary of keys and values
dict = containers.Map(keys,values);
%save dict to mat file which we can later use to access data
list = {'dia_start','dia_max1','dia_max2','dia_max3','dia_max4','dia_max5','dia_max6','dia_end',...
    'dia_min1','dia_min2','dia_min3','dia_min4','dia_min5',...
    'springyoungmodulus','friction_coeff','springmeshSize'};

save(matfilename,'result','keys','values','dict','wire_dia',...
    'springyoungmodulus','friction_coeff','springmeshSize',...
    'dia_start','dia_max1','dia_max2','dia_max3','dia_max4','dia_max5','dia_max6','dia_end',...
    'dia_min1','dia_min2','dia_min3','dia_min4','dia_min5','angle_pts','height_pts','list');

setpref('Internet','SMTP_Server','smtp.purdue.edu');
setpref('Internet','E_mail','deshmuk5@purdue.edu');
sendmail('deshmuk5@purdue.edu','MATLAB says',strcat('My lord I have finished simulation of ',parent_dir,' at ',datestr(now)));

%exit;
