function [sideforce,axialforce,displacement]=readdata(filepath)
%This function will read the txt files generated by abaqus.py and will
%write the data into the variables
fID = fopen(strcat(filepath,'sideforce.txt'),'r');
fgetl(fID);
more = true;
sideforce = [];
while more
   [data more]=fscanf(fID,'%f',3);
   if more
       sideforce = [sideforce; data'];
   end
end
fclose(fID);

fID = fopen(strcat(filepath,'axialforce.txt'),'r');
fgetl(fID);
more = true;
axialforce = [];
while more
   [data more]=fscanf(fID,'%f',1);
   if more
       axialforce = [axialforce data];
   end
end
fclose(fID);

fID = fopen(strcat(filepath,'displacement.txt'),'r');
fgetl(fID);
more = true;
displacement = [];
while more
   [data more]=fscanf(fID,'%f',1);
   if more
       displacement = [displacement data];
   end
end
fclose(fID);

end